language: generic
sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install sed git build-essential autoconf autotools-dev libtool wget scons bison re2c libboost-all-dev python-dev libpython-all-dev libcurl4-openssl-dev libbz2-dev

script:
  - export PYTHON_BIN=python2.7
  - ./bootstrap.sh
  - ./configure CXXFLAGS=-fPIC LOCAL_PLUGIN_DIR=plugins --enable-python --enable-shared=no --enable-static-boost
  - make

after_failure:
  - cat config.log
