language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libboost-all-dev

script:
  - export PYTHON_BIN=python2.7
  - ./bootstrap.sh
  - ./configure CXXFLAGS=-fPIC LOCAL_PLUGIN_DIR=plugins --enable-python --enable-shared=no --enable-static-boost
  - make

after_failure:
  - cat config.log
