language: generic

matrix:
  include:
    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   env: BUILDTYPE=linux
    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   env: BUILDTYPE=windows
    - os: osx
      env: BUILDTYPE=osx

before_install:
  - ./scripts/check-${BUILDTYPE}.sh --install-dependencies

script:
  - ./scripts/make-${BUILDTYPE}.sh --verbose

after_failure:
  - cat config.log
